### ISSUE TITLE
Hardcoded binding for dead letter queue with customer in name

### ISSUE THREAD

**Issue by mikr123** [ZenWave360/zenwave-sdk#10]
https://github.com/ZenWave360/zenwave-sdk/blob/1b2554773029f13a2687ee620f21b88c9ee5038b/plugins/asyncapi-spring-cloud-streams3/src/main/resources/io/zenwave360/sdk/plugins/SpringCloudStream3Generator/consumer/imperative/Consumer.java.hbs#LL43C5-L43C104

`@Value("#{${spring.cloud.stream.bindings.on-customer-event-in-0.dead-letter-queue-error-map:{:}}}")`

**Comment by ivangsa** [comment]
Hi @mikr123 

I'm sorry I didn't see this until now..

I will release a fix soon, and thanks for reporting this!

**Comment by ivangsa** [comment]
Version https://github.com/ZenWave360/zenwave-sdk/releases/tag/v1.0.7 have been deployed to maven central.
