### ISSUE TITLE
Problem Configuring Proxy with JBang

### ISSUE THREAD

**Issue by gwentey** [ZenWave360/zenwave-sdk#12]
Hello,

I am currently facing an issue with JBang that doesn't allow configuring a proxy, and this seems to be a problem that has persisted for some time. This presents challenges when using ZenWave SDK via JBang because our environment requires a proxy for network connections.

I've been trying to make ZenWave SDK work without JBang by manually retrieving the plugins and integrating them into my project's pom.xml file. However, this process is proving to be tedious and impractical.

However, I want to emphasize that ZenWave SDK is an extremely convenient and powerful tool for software development, and I am grateful for this initiative. It offers outstanding features for Domain Driven Design (DDD) and API-First modeling, making it extremely valuable for our work. It's a valuable resource for the development community.

I wonder if there is another solution or a way to make ZenWave SDK work without relying on JBang. Could you consider using another tool or providing detailed instructions for manually integrating the plugins into a Maven project without depending on JBang?

I believe that solving this issue would be beneficial for many users who encounter similar challenges. Thank you in advance for your assistance and guidance, and once again, congratulations on this fantastic tool.

**Comment by maxandersen** [comment]
What is your problem with jbang and proxies ?

Jbang uses normal java http client which honors proxy configuration. If it does not that is a bug and we should fix that.

**Comment by gwentey** [comment]
We can't set a proxy with credentials : [issues/1694](https://github.com/jbangdev/jbang/issues/1694)

**Comment by maxandersen** [comment]
I've commented on that issue since then. Have you tried out that better documented approach ? Does it work or fail for your proxy?

**Comment by ivangsa** [comment]
First of all, thanks @maxandersen for jumping in, always so responsibe with JBang <3

I just realize, I had set the notification to only 'mentions' so I was missing this threads (which is not what I wanted)

@gwentey I hope the last instructions posted by Max allow you go through your proxy..

You can always create an standalone fat-jar including zenwave-cli and the list of plugins you need:

<details>
    <summary>Click to expand pom.xml</summary>

```xml
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>not-used</groupId>
  <artifactId>zenwave-cli</artifactId>
  <version>standalone</version>

      <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
        <maven-jar-plugin.version>3.2.0</maven-jar-plugin.version>
        <maven-javadoc-plugin.version>3.1.1</maven-javadoc-plugin.version>
        <maven-project-info-reports-plugin.version>3.0.0</maven-project-info-reports-plugin.version>
        <maven-release-plugin.version>2.5.3</maven-release-plugin.version>

        <zenwave.version>1.4.0-SNAPSHOT</zenwave.version>
    </properties>

  <dependencies>
    <dependency>
      <groupId>io.github.zenwave360.zenwave-sdk</groupId>
      <artifactId>zenwave-sdk-cli</artifactId>
      <version>${zenwave.version}</version>
    </dependency>

    <dependency>
      <groupId>io.github.zenwave360.zenwave-sdk.plugins</groupId>
      <artifactId>asyncapi-spring-cloud-streams3</artifactId>
      <version>${zenwave.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.zenwave360.zenwave-sdk.plugins</groupId>
      <artifactId>asyncapi-jsonschema2pojo</artifactId>
      <version>${zenwave.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.zenwave360.zenwave-sdk.plugins</groupId>
      <artifactId>openapi-spring-webtestclient</artifactId>
      <version>${zenwave.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.zenwave360.zenwave-sdk.plugins</groupId>
      <artifactId>openapi-rest-assured</artifactId>
      <version>${zenwave.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.zenwave360.zenwave-sdk.plugins</groupId>
      <artifactId>backend-application-default</artifactId>
      <version>${zenwave.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.zenwave360.zenwave-sdk.plugins</groupId>
      <artifactId>zdl-to-openapi</artifactId>
      <version>${zenwave.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.zenwave360.zenwave-sdk.plugins</groupId>
      <artifactId>zdl-to-asyncapi</artifactId>
      <version>${zenwave.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.zenwave360.zenwave-sdk.plugins</groupId>
      <artifactId>jdl-to-asyncapi</artifactId>
      <version>${zenwave.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.zenwave360.zenwave-sdk.plugins</groupId>
      <artifactId>zdl-to-markdown</artifactId>
      <version>${zenwave.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.zenwave360.zenwave-sdk.plugins</groupId>
      <artifactId>openapi-controllers</artifactId>
      <version>${zenwave.version}</version>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>1.7.36</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
           <phase>package</phase>
           <goals>
              <goal>shade</goal>
           </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```
</details>

Package & run it with:

```sh
mvn package
java -jar target/zenwave-cli-standalone.jar -h list
```

So it will use your maven setting to download everything.
