### ISSUE TITLE
[Bug]: Nested references don't resolve for Async2Pojo generation

### ISSUE THREAD

**Issue by saturna** [ZenWave360/zenwave-sdk#37]
### ZenWave Version

1.6.0

### Execution Environment

JBang Alias (CLI)

### ZenWave Plugin

AsyncApiJsonSchema2PojoPlugin

### What happened?

This seems similar to https://github.com/ZenWave360/zenwave-sdk/issues/1

When I have a nested schema structure such as A->B->C, only B will resolve and C will not be present in the generated code.

Example schema that reproduces the issue:

```
asyncapi: '2.6.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  exampleOp:
    subscribe:
      operationId: exampleOp
      message:
        $ref: '#/components/messages/ExampleMessage'
components:
  messages:
    ExampleMessage:
      payload:
        $ref: '#/components/schemas/Car'
  schemas:
    Base:
      type: object
      additionalProperties: false
      title: Base
      properties:
        reference:
          type: string
    Engine:
      title: Engine
      allOf:
        - $ref: '#/components/schemas/Base'
        - type: object
          title: Engine
          additionalProperties: false
          properties:
            mileage:
              type: string
    Car:
      title: Car
      allOf:
        - $ref: '#/components/schemas/Engine'
        - type: object
          title: Car
          additionalProperties: false
          properties:
            make:
              type: string
```
In above example, Car will not be generated, only Engine

**Comment by ivangsa** [comment]
confirmed, there is a problem in https://www.zenwave360.io/json-schema-ref-parser-jvm/

this is the schema resolved after bundling all `$refs` and merging `allOf`s

```json
{
  "additionalProperties" : false,
  "type" : "object",
  "title" : "Engine",
  "properties" : {
    "reference" : {
      "type" : "string"
    },
    "mileage" : {
      "type" : "string"
    }
  }
}
```

**Comment by ivangsa** [comment]
hi @saturna thanks for reporting this issue

a fix has been released for the upstream library and it will be released for zenwave-sdk in the comming days

**Comment by saturna** [comment]
Thank you for delivering the fix so quickly!  🙏

**Comment by ivangsa** [comment]
(maybe you can star it, that would help bring awarenes)
